apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: h2fleet
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - toggle-service.yaml
  - fleet-api.yaml
  - infra-api.yaml
  - citizen-api.yaml
  - commerce-api.yaml
  - telemetry-ingest.yaml
  - digital-twin.yaml
  - predictive-maintenance.yaml
  - route-optimizer.yaml
  - carbon-analytics.yaml
  - pwa.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: h2fleet
